In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
battles_file = "data/battles.csv"
battles_df = pd.read_csv(battles_file)
battles_df.head()

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,...,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN
2,Battle of Riverrun,298,3,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,1.0,15000.0,10000.0,"Jaime Lannister, Andros Brax","Edmure Tully, Tytos Blackwood",1.0,Riverrun,The Riverlands,NaN
3,Battle of the Green Fork,298,4,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,1.0,18000.0,20000.0,"Roose Bolton, Wylis Manderly, Medger Cerwyn, H...","Tywin Lannister, Gregor Clegane, Kevan Lannist...",1.0,Green Fork,The Riverlands,NaN
4,Battle of the Whispering Wood,298,5,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,1875.0,6000.0,"Robb Stark, Brynden Tully",Jaime Lannister,1.0,Whispering Wood,The Riverlands,NaN

In [12]:
deaths_file = "data/character-deaths.csv"
deaths_df = pd.read_csv(deaths_file)
deaths_df.head(100)

,Name,Allegiances,Death Year,Book of Death,Death Chapter,Book Intro Chapter,Gender,Nobility,GoT,CoK,SoS,FfC,DwD
0,Addam Marbrand,Lannister,NaN,NaN,NaN,56.0,1,1,1,1,1,1,0
1,Aegon Frey (Jinglebell),None,299.0,3.0,51.0,49.0,1,1,0,0,1,0,0
2,Aegon Targaryen,House Targaryen,NaN,NaN,NaN,5.0,1,1,0,0,0,0,1
3,Adrack Humble,House Greyjoy,300.0,5.0,20.0,20.0,1,1,0,0,0,0,1
4,Aemon Costayne,Lannister,NaN,NaN,NaN,NaN,1,1,0,0,1,0,0
5,Aemon Estermont,Baratheon,NaN,NaN,NaN,NaN,1,1,0,1,1,0,0
6,Aemon Targaryen (son of Maekar I),Night's Watch,300.0,4.0,35.0,21.0,1,1,1,0,1,1,0
7,Aenys Frey,None,300.0,5.0,NaN,59.0,0,1,1,1,1,0,1
8,Aeron Greyjoy,House Greyjoy,NaN,NaN,NaN,11.0,1,1,0,1,0,1,0
9,Aethan,Night's Watch,NaN,NaN,NaN,0.0,1,0,0,0,1,0,0
10,Aggar,House Greyjoy,299.0,2.0,56.0,50.0,1,0,0,1,0,0,0
11,Aggo,House Targaryen,NaN,NaN,NaN,54.0,1,0,1,1,1,0,1
12,Alan of Rosby,Night's Watch,300.0,5.0,4.0,18.0,1,1,0,1,1,0,1
13,Alayaya,None,NaN,NaN,NaN,15.0,0,0,0,1,0,0,0
14,Albar Royce,Arryn,NaN,NaN,NaN,38.0,1,1,1,0,0,1,0
15,Albett,Night's Watch,NaN,NaN,NaN,26.0,1,0,1,0,0,0,0
16,Alebelly,House Stark,299.0,2.0,46.0,4.0,1,0,0,1,0,0,0
17,Alerie Hightower,House Tyrell,NaN,NaN,NaN,6.0,0,1,0,0,1,1,0
18,Alesander Staedmon,Baratheon,NaN,NaN,NaN,65.0,1,1,0,1,0,0,0
19,Alester Florent,Baratheon,300.0,4.0,NaN,36.0,1,1,0,1,1,0,0
20,Alia of Braavos,None,NaN,NaN,NaN,28.0,0,0,1,0,0,0,0
21,Alla Tyrell,House Tyrell,NaN,NaN,NaN,6.0,0,1,0,0,1,1,0
22,Allard Seaworth,Baratheon,299.0,2.0,10.0,10.0,1,1,0,1,0,0,0
23,Alliser Thorne,Night's Watch,NaN,NaN,NaN,19.0,1,0,1,1,1,0,1
24,Alyn,House Stark,298.0,3.0,34.0,12.0,1,0,1,0,0,0,0
25,Alyn Ambrose,Tyrell,NaN,NaN,NaN,59.0,1,1,0,1,0,1,0
26,Alyn Estermont,Baratheon,NaN,NaN,NaN,NaN,1,1,0,1,1,0,0
27,Alyn Stackspear,Lannister,NaN,NaN,NaN,16.0,1,1,0,0,0,1,0
28,Alys Karstark,Stark,NaN,NaN,NaN,44.0,0,1,0,0,0,0,1
29,Alysane Mormont,Stark,NaN,NaN,NaN,35.0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Bayard Norcross,Tyrell,NaN,NaN,NaN,28.0,1,1,0,0,0,1,0
71,Bearded Ben,Night's Watch,NaN,NaN,NaN,NaN,1,0,0,0,0,1,0
72,Becca,House Arryn,NaN,NaN,NaN,12.0,0,0,1,0,0,0,0
73,Becca the Baker,None,299.0,3.0,34.0,34.0,0,0,0,0,1,0,0
74,Bedwyck,Night's Watch,NaN,NaN,NaN,13.0,1,0,0,1,1,0,1
75,Belaquo,None,NaN,NaN,NaN,52.0,1,0,0,0,0,0,1
76,Bella,None,NaN,NaN,NaN,29.0,0,0,0,0,1,0,0
77,Bellegere Otherys (courtesan),None,NaN,NaN,NaN,34.0,0,1,0,0,0,1,0
78,Bellonara Otherys,None,NaN,NaN,NaN,34.0,0,1,0,0,0,1,0
79,Belwas,House Targaryen,NaN,NaN,NaN,63.0,1,0,0,1,1,0,1
80,Ben,None,NaN,NaN,NaN,37.0,1,0,0,0,0,1,0
81,Ben Bones,None,NaN,NaN,NaN,12.0,1,0,0,0,0,0,1
82,Ben Plumm,None,NaN,NaN,NaN,57.0,1,0,0,0,1,0,1
83,Benedar Belmore,Arryn,NaN,NaN,NaN,23.0,1,1,0,0,0,1,0
84,Benfred Tallhart,Stark,299.0,2.0,37.0,16.0,1,1,0,1,0,0,0
85,Benfrey Frey,None,299.0,5.0,51.0,51.0,1,1,0,0,1,0,0
86,Benjen Stark,Night's Watch,298.0,1.0,24.0,5.0,1,1,1,0,0,0,0
87,Bennet,None,300.0,4.0,31.0,31.0,1,0,0,0,0,1,0
88,Beric Dondarrion,None,300.0,4.0,27.0,42.0,1,1,1,0,1,0,0
89,Bessa (Winterfell),Stark,NaN,NaN,NaN,37.0,0,0,1,0,0,0,0
90,Beth Cassel,Stark,NaN,NaN,NaN,7.0,0,1,1,1,0,0,0
91,Bhakaz zo Loraq,None,NaN,NaN,NaN,2.0,1,1,0,0,0,0,1
92,Big Boil,Wildling,NaN,NaN,NaN,41.0,1,0,0,0,1,0,0
93,Big Walder Frey,None,NaN,NaN,NaN,NaN,1,1,1,1,0,0,1
94,Biter,None,300.0,4.0,37.0,1.0,1,0,0,1,0,1,0
95,Black Bernarr,Night's Watch,NaN,NaN,NaN,18.0,1,0,0,0,1,0,1
96,Black Walder Frey,None,NaN,NaN,NaN,35.0,1,1,0,0,1,0,0
97,Blane,Night's Watch,NaN,NaN,NaN,23.0,1,0,0,1,0,0,0
98,Bloodbeard,None,NaN,NaN,NaN,25.0,1,0,0,0,0,0,1
99,Blue Bard,House Tyrell,NaN,NaN,NaN,12.0,1,0,0,0,0,1,0

In [4]:
predictions_file = "data/character-predictions.csv"
predictions_df = pd.read_csv(predictions_file)
predictions_df.head()

,S.No,actual,pred,alive,plod,name,title,male,culture,dateOfBirth,...,isAliveHeir,isAliveSpouse,isMarried,isNoble,age,numDeadRelations,boolDeadRelations,isPopular,popularity,isAlive
0,1,0,0,0.054,0.946,Viserys II Targaryen,NaN,1,NaN,NaN,...,0.0,NaN,0,0,NaN,11,1,1,0.605351,0
1,2,1,0,0.387,0.613,Walder Frey,Lord of the Crossing,1,Rivermen,208.0,...,NaN,1.0,1,1,97.0,1,1,1,0.896321,1
2,3,1,0,0.493,0.507,Addison Hill,Ser,1,NaN,NaN,...,NaN,NaN,0,1,NaN,0,0,0,0.267559,1
3,4,0,0,0.076,0.924,Aemma Arryn,Queen,0,NaN,82.0,...,NaN,0.0,1,1,23.0,0,0,0,0.183946,0
4,5,1,1,0.617,0.383,Sylva Santagar,Greenstone,0,Dornish,276.0,...,NaN,1.0,1,1,29.0,0,0,0,0.043478,1

In [5]:
# Specify which columns from deaths_df we want for characters table
deaths_cols = ["Name", "Allegiances", "Gender", "GoT", "CoK", "SoS", "FfC", "DwD"]
deaths_transformed = deaths_df[deaths_cols].copy()

# Rename the columns 
deaths_transformed = deaths_transformed.rename(columns={"Name": "CharacterName",
                                                        "Allegiances": "House",
                                                        "Gender": "Gender",
                                                        "GoT": "Book1",
                                                        "CoK": "Book2",
                                                        "SoS": "Book3",
                                                        "FfC": "Book4",
                                                        "DwD": "Book5"
                                                        })

deaths_transformed.set_index("CharacterName", inplace=True)
deaths_transformed.head(100)

,House,Gender,Book1,Book2,Book3,Book4,Book5
CharacterName,,,,,,,
Addam Marbrand,Lannister,1,1,1,1,1,0
Aegon Frey (Jinglebell),None,1,0,0,1,0,0
Aegon Targaryen,House Targaryen,1,0,0,0,0,1
Adrack Humble,House Greyjoy,1,0,0,0,0,1
Aemon Costayne,Lannister,1,0,0,1,0,0
Aemon Estermont,Baratheon,1,0,1,1,0,0
Aemon Targaryen (son of Maekar I),Night's Watch,1,1,0,1,1,0
Aenys Frey,None,0,1,1,1,0,1
Aeron Greyjoy,House Greyjoy,1,0,1,0,1,0
Aethan,Night's Watch,1,0,0,1,0,0
Aggar,House Greyjoy,1,0,1,0,0,0
Aggo,House Targaryen,1,1,1,1,0,1
Alan of Rosby,Night's Watch,1,0,1,1,0,1
Alayaya,None,0,0,1,0,0,0
Albar Royce,Arryn,1,1,0,0,1,0
Albett,Night's Watch,1,1,0,0,0,0
Alebelly,House Stark,1,0,1,0,0,0
Alerie Hightower,House Tyrell,0,0,0,1,1,0
Alesander Staedmon,Baratheon,1,0,1,0,0,0
Alester Florent,Baratheon,1,0,1,1,0,0
Alia of Braavos,None,0,1,0,0,0,0
Alla Tyrell,House Tyrell,0,0,0,1,1,0
Allard Seaworth,Baratheon,1,0,1,0,0,0
Alliser Thorne,Night's Watch,1,1,1,1,0,1
Alyn,House Stark,1,1,0,0,0,0
Alyn Ambrose,Tyrell,1,0,1,0,1,0
Alyn Estermont,Baratheon,1,0,1,1,0,0
Alyn Stackspear,Lannister,1,0,0,0,1,0
Alys Karstark,Stark,0,0,0,0,0,1
Alysane Mormont,Stark,0,0,0,0,0,1
...,...,...,...,...,...,...,...
Bayard Norcross,Tyrell,1,0,0,0,1,0
Bearded Ben,Night's Watch,1,0,0,0,1,0
Becca,House Arryn,0,1,0,0,0,0
Becca the Baker,None,0,0,0,1,0,0
Bedwyck,Night's Watch,1,0,1,1,0,1
Belaquo,None,1,0,0,0,0,1
Bella,None,0,0,0,1,0,0
Bellegere Otherys (courtesan),None,0,0,0,0,1,0
Bellonara Otherys,None,0,0,0,0,1,0
Belwas,House Targaryen,1,0,1,1,0,1
Ben,None,1,0,0,0,1,0
Ben Bones,None,1,0,0,0,0,1
Ben Plumm,None,1,0,0,1,0,1
Benedar Belmore,Arryn,1,0,0,0,1,0
Benfred Tallhart,Stark,1,0,1,0,0,0
Benfrey Frey,None,1,0,0,1,0,0
Benjen Stark,Night's Watch,1,1,0,0,0,0
Bennet,None,1,0,0,0,1,0
Beric Dondarrion,None,1,1,0,1,0,0
Bessa (Winterfell),Stark,0,1,0,0,0,0
Beth Cassel,Stark,0,1,1,0,0,0
Bhakaz zo Loraq,None,1,0,0,0,0,1
Big Boil,Wildling,1,0,0,1,0,0
Big Walder Frey,None,1,1,1,0,0,1
Biter,None,1,0,1,0,1,0
Black Bernarr,Night's Watch,1,0,0,1,0,1
Black Walder Frey,None,1,0,0,1,0,0
Blane,Night's Watch,1,0,1,0,0,0
Bloodbeard,None,1,0,0,0,0,1
Blue Bard,House Tyrell,1,0,0,0,1,0

In [6]:
# Specify which columns from deaths_df we want
battles_cols = ["name", "battle_number", "year", "attacker_1", "defender_1", "attacker_outcome"]
battles_transformed = battles_df[battles_cols].copy()

# Rename the columns 
battles_transformed = battles_transformed.rename(columns={"name": "BattleName",
                                                          "battle_number": "Battle_ID",
                                                          "year": "Battle_Year",
                                                          "attacker_1": "Attacker",
                                                          "defender_1": "Defender",
                                                          "attacker_outcome": "Attacker_Outcome"
                                                        })
battles_transformed.set_index("BattleName", inplace=True)
battles_transformed.head(100)

,Battle_ID,Battle_Year,Attacker,Defender,Attacker_Outcome
BattleName,,,,,
Battle of the Golden Tooth,1,298,Lannister,Tully,win
Battle at the Mummer's Ford,2,298,Lannister,Baratheon,win
Battle of Riverrun,3,298,Lannister,Tully,win
Battle of the Green Fork,4,298,Stark,Lannister,loss
Battle of the Whispering Wood,5,298,Stark,Lannister,win
Battle of the Camps,6,298,Stark,Lannister,win
Sack of Darry,7,298,Lannister,Darry,win
Battle of Moat Cailin,8,299,Greyjoy,Stark,win
Battle of Deepwood Motte,9,299,Greyjoy,Stark,win
Battle of the Stony Shore,10,299,Greyjoy,Stark,win
Battle of Torrhen's Square,11,299,Stark,Greyjoy,win
Battle of Winterfell,12,299,Greyjoy,Stark,win
Sack of Torrhen's Square,13,299,Greyjoy,Stark,win
Sack of Winterfell,14,299,Bolton,Stark,win
Battle of Oxcross,15,299,Stark,Lannister,win
Siege of Storm's End,16,299,Baratheon,Baratheon,win
Battle of the Fords,17,299,Lannister,Tully,loss
Sack of Harrenhal,18,299,Stark,Lannister,win
Battle of the Crag,19,299,Stark,Lannister,win
Battle of the Blackwater,20,299,Baratheon,Lannister,loss
Siege of Darry,21,299,Darry,Lannister,win
Battle of Duskendale,22,299,Stark,Lannister,loss
Battle of the Burning Septry,23,299,Brotherhood without Banners,Brave Companions,win
Battle of the Ruby Ford,24,299,Lannister,Stark,win
Retaking of Harrenhal,25,299,Lannister,Brave Companions,win
The Red Wedding,26,299,Frey,Stark,win
Siege of Seagard,27,299,Frey,Mallister,win
Battle of Castle Black,28,300,Free folk,Night's Watch,loss
Fall of Moat Cailin,29,300,Bolton,Greyjoy,win
Sack of Saltpans,30,300,Brave Companions,NaN,win
Retaking of Deepwood Motte,31,300,Baratheon,Greyjoy,win
Battle of the Shield Islands,32,300,Greyjoy,Tyrell,win
"Invasion of Ryamsport, Vinetown, and Starfish Harbor",33,300,Greyjoy,Tyrell,win
Second Seige of Storm's End,34,300,Baratheon,Baratheon,win
Siege of Dragonstone,35,300,Baratheon,Baratheon,win
Siege of Riverrun,36,300,Lannister,Tully,win
Siege of Raventree,37,300,Bracken,Blackwood,win
Siege of Winterfell,38,300,Baratheon,Bolton,NaN

In [7]:
# Specify which columns from deaths_df we want
predictions_cols = ["name", "popularity"]
predictions_transformed = predictions_df[predictions_cols].copy()

# Rename the columns 
predictions_transformed = predictions_transformed.rename(columns={"name": "CharacterName",
                                                                  "popularity": "Popularity"
                                                                 })
predictions_transformed.set_index("CharacterName", inplace=True)
predictions_transformed.head(100)

                                          Popularity
CharacterName
Viserys II Targaryen                        0.605351
Walder Frey                                 0.896321
Addison Hill                                0.267559
Aemma Arryn                                 0.183946
Sylva Santagar                              0.043478
Tommen Baratheon                            1.000000
Valarr Targaryen                            0.431438
Viserys I Targaryen                         0.678930
Wilbert                                     0.006689
Wilbert Osgrey                              0.020067
Will                                        0.163880
Will (orphan)                               0.003344
Will (squire)                               0.003344
Will (Standfast)                            0.003344
Will (Treb)                                 0.003344
Will Humble                                 0.013378
Willam                                      0.013378
Willem Wylde                                0.020067
Willifer                                    0.006689
Willit                                      0.010033
Willis Wode                                 0.020067
Willis Fell                                 0.023411
Willow Heddle                               0.033445
Willum                                      0.000000
Wolmer                                      0.003344
Willow Witch-eye                            0.050167
Woth                                        0.030100
Wulfe                                       0.023411
Wyl the Whittler                            0.006689
Wyl (guard)                                 0.026756
...                                              ...
Rainbow Knight                              0.003344
Randa                                       0.003344
Rast                                        0.066890
Rawney                                      0.010033
Raymar Royce                                0.013378
Raymond Nayland                             0.016722
Raymund Tyrell                              0.127090
Red Oarsman                                 0.016722
Red Lamb                                    0.000000
Redtusk                                     0.016722
Red Rolfe                                   0.013378
Redwyn                                      0.006689
Reynard Webber                              0.006689
Reysen                                      0.023411
Rhaegel Targaryen                           0.096990
Rhaena Targaryen (daughter of Daemon)       0.143813
Rhaena Targaryen (daughter of Aegon III)    0.073579
Rhaenys Targaryen                           0.277592
Rhaenys Targaryen (daughter of Rhaegar)     0.244147
Rhialta Vance                               0.016722
Rhaenys Targaryen (daughter of Aemon)       0.143813
Rhonda Rowan                                0.050167
Richard Farrow                              0.016722
Richard Lonmouth                            0.023411
Rigney                                      0.003344
Rob                                         0.003344
Rickard Tyrell                              0.123746
Robb Reyne                                  0.006689
Robert Ashford                              0.023411
Robert Brax (son of Flement)                0.120401

[100 rows x 1 columns]

In [15]:
# Specify which columns from deaths_df we want for characters table
deaths2_cols = ["Name", "Death Year", "Book of Death"]
deaths2_transformed = deaths_df[deaths2_cols].copy()

# Rename the columns 
deaths2_transformed = deaths2_transformed.rename(columns={"Name": "CharacterName",
                                                        "Death Year": "DeathYear",
                                                        "Book of Death": "Book_of_Death"
                                                        })
deaths2_transformed = deaths2_transformed.dropna(subset=['Book_of_Death'])

deaths2_transformed.set_index("CharacterName", inplace=True)
deaths2_transformed.head(100)

                                   DeathYear  Book_of_Death
CharacterName
Aegon Frey (Jinglebell)                299.0            3.0
Adrack Humble                          300.0            5.0
Aemon Targaryen (son of Maekar I)      300.0            4.0
Aenys Frey                             300.0            5.0
Aggar                                  299.0            2.0
Alan of Rosby                          300.0            5.0
Alebelly                               299.0            2.0
Alester Florent                        300.0            4.0
Allard Seaworth                        299.0            2.0
Alyn                                   298.0            3.0
Amory Lorch                            299.0            2.0
Anvil Ryn                              299.0            3.0
Aron Santagar                          299.0            2.0
Arys Oakheart                          300.0            4.0
Bannen                                 299.0            3.0
Barra                                  299.0            2.0
Barsena                                300.0            5.0
Becca the Baker                        299.0            3.0
Benfred Tallhart                       299.0            2.0
Benfrey Frey                           299.0            5.0
Benjen Stark                           298.0            1.0
Bennet                                 300.0            4.0
Beric Dondarrion                       300.0            4.0
Biter                                  300.0            4.0
Brown Bernarr                          299.0            3.0
Bryan Fossoway                         299.0            2.0
Bryce Caron                            299.0            2.0
Bryen Farring                          300.0            5.0
Burton Crakehall                       299.0            2.0
Byam Flint                             299.0            3.0
...                                      ...            ...
Ebben                                  299.0            2.0
Eddard Karstark                        298.0            1.0
Eddard Stark                           299.0            1.0
Emmon Cuy                              299.0            2.0
Elwood                                 299.0            3.0
Endrew Tarth                           299.0            3.0
Eon Hunter                             300.0            3.0
Eroeh                                  298.0            1.0
Falyse Stokeworth                      300.0            5.0
Farlen                                 299.0            2.0
Fletcher Will                          299.0            3.0
Fogo                                   298.0            1.0
Frenya                                 300.0            5.0
Gared                                  297.0            1.0
Garse Goodbrook                        299.0            3.0
Garth Greyfeather                      300.0            5.0
Garth of Greenaway                     300.0            5.0
Garth of Oldtown                       299.0            3.0
Gelmarr                                299.0            2.0
Gerren                                 299.0            2.0
Gevin Harlaw                           299.0            2.0
Gladden Wylde                          298.0            1.0
Grazdan                                299.0            3.0
Grazdan mo Ullhor                      299.0            3.0
Gregor Clegane                         300.0            4.0
Groleo                                 300.0            5.0
Grubbs                                 300.0            5.0
Guncer Sunglass                        299.0            3.0
Guyard Morrigen                        299.0            2.0
Gyles Rosby                            300.0            4.0

[100 rows x 2 columns]

In [16]:
rds_connection_string = "root:V@larmorghulis19@127.0.0.1/ETLofThrones"
engine = create_engine(f'mysql+pymysql://{rds_connection_string}')

In [17]:
engine.table_names()

['Battles', 'Characters', 'Deaths', 'Discussion']

In [18]:
deaths2_transformed.to_sql(name='Deaths', con=engine, if_exists='append', index=True)

In [ ]:
#deaths_transformed.to_sql(name='Characters', con=engine, if_exists='append', index=True)

In [ ]:
#battles_transformed.to_sql(name='Battles', con=engine, if_exists='append', index=True)

In [ ]:
#predictions_transformed.to_sql(name='Discussion', con=engine, if_exists='append', index=True)

## TODO
1. Create a transformed df for deaths with death year, book of death, Name. Then send to sql as Deaths table.
2. Append all tables in SQL with primary keys, 
3. Connect on primary keys